#! /bin/bash                                    # code start
My_shell="hey "                                 # variable declaration
echo "${My_shell}there my name is Akshat"       # output syntax

output: 
Hey there my name is Akshat

